  - name: determine swarm status
    shell: >
      docker info | egrep '^Swarm: ' | cut -d ' ' -f2
    register: swarm_status

  - debug: var=swarm_status

  - name: Create a stack pnps and up the services
    command: "docker stack deploy -c {{ source_path }}/docker-production.yml {{ stack_name }}"
    when: "'active' in swarm_status.stdout_lines"