# Generated by Django 2.2.14 on 2021-08-02 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='hora_acc',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='hora_atividade',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='nivel_participacao',
        ),
        migrations.CreateModel(
            name='NivelParticipacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('nivel_participacao', models.CharField(max_length=50)),
                ('hora_atividade', models.IntegerField()),
                ('hora_acc', models.IntegerField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.Atividade')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivelparticipacao_informer', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivelparticipacao_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nivel',
                'verbose_name_plural': 'niveis',
            },
        ),
    ]
