# Generated by Django 2.2.14 on 2021-08-06 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0004_auto_20210805_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissaoResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_ok', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, max_length=250, null=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.Certificado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissaoresponse_informer', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissaoresponse_updater', to=settings.AUTH_USER_MODEL)),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.Submicao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
