#
# Hot deploy
#

- hosts:
    - local-host
  roles:
    - role: code-tag-diff

- hosts:
    - bridge-server
  become: yes
  become_method: sudo
  vars:
    files: "{{ hostvars['localhost']['modified_files'].stdout_lines }}"
  roles:
    - role: code-send-hot
